# -*- coding: utf-8 -*-
"""data_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1laxFklIrkd0AxHZat3A6Djydqpo2EHa9

#This code is written by Mehran Dibaji, for Launchpad demo
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive')

# Example path for a file in your main 'My Drive' folder
#file_path = '/content/drive'

df = pd.read_csv('/content/drive/My Drive/Colab Notebooks/SMART/20240115_145848-AD23L00131-end_of_line.csv')

df_eol_orig.head()

df_eol_orig = pd.read_csv('/content/drive/Othercomputers/My MacBook Air/Desktop/smart/20240115_145848-AD23L00131-end_of_line.csv')
df_eol_orig.head()

# unit conversions
df_eol = df_eol_orig.copy()
df_eol = df_eol.rename(columns={'creationDateTime': 'time', 'I_IEP_POS': 'I'})
df_eol['BMS_TEMP'] = df_eol['BMS_TEMP']/10 #degC
df_eol['BMS_STRING_V'] = df_eol['BMS_STRING_V']/1000 #V
df_eol['time'] = df_eol['time']/(1000) #second

# Calculate min and max for each column
min_max_values = df_eol.agg(['min', 'max'])

# Print the results
print(min_max_values)

# delta timestamps

gap = df_eol.time.diff()
print(gap.unique())

# voltage
plt.figure(figsize=(7,5))

for index in sorted(df_eol['BMS_STRING_INDEX'].unique()):
    df_subset = df_eol[df_eol['BMS_STRING_INDEX'] == index]
    plt.plot(df_subset['time']/60, df_subset['BMS_STRING_V'], label=f'{index}')

plt.xlabel('Time (minutes)')
plt.ylabel('BMS_STRING_V (V)')
plt.title('String Voltage vs Time')
plt.legend(title='BMS_STRING_INDEX')
plt.grid(True, linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

# Pivot for voltage
pivot_v = df_eol.pivot(index='time', columns='BMS_STRING_INDEX', values='BMS_STRING_V')

# Interpolate missing data along the time index
pivot_v_interp = pivot_v.interpolate(method='linear', limit_direction='both')

# Aggregate across strings (columns) for each time
agg_v = pd.DataFrame({
    'V_min': pivot_v_interp.min(axis=1),
    'V_max': pivot_v_interp.max(axis=1),
    'V_avg': pivot_v_interp.mean(axis=1)
})

# time as a column
agg_v = agg_v.reset_index()

print(agg_v.head())

plt.figure(figsize=(7,5))

plt.plot(agg_v['time']/60, agg_v['V_min'], label='V_min',color='blue')
plt.plot(agg_v['time']/60, agg_v['V_max'], label='V_max',color='red')
plt.plot(agg_v['time']/60, agg_v['V_avg'], label='V_avg',color='black', linestyle='--')

plt.xlabel('Time (minutes)')
plt.ylabel('Voltage (V)')
plt.title('Min, Max, and Average Voltages Over Time')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

# temperature
plt.figure(figsize=(7,5))

for index in sorted(df_eol['BMS_TEMP_INDEX'].unique()):
    df_subset = df_eol[df_eol['BMS_TEMP_INDEX'] == index]
    plt.plot(df_subset['time']/60, df_subset['BMS_TEMP'], label=f'{index}')

plt.xlabel('Time (minutes)')
plt.ylabel('BMS_TEMP (C)')
plt.title('Temperature vs Time')
plt.legend(title='Sensor #')
plt.grid(True, linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

# Pivot for temperature
pivot_t = df_eol.pivot(index='time', columns='BMS_TEMP_INDEX', values='BMS_TEMP')

# Interpolate missing data along the time index
pivot_t_interp = pivot_t.interpolate(method='linear', limit_direction='both')

agg_t = pd.DataFrame({
    'T_min': pivot_t_interp.min(axis=1),
    'T_max': pivot_t_interp.max(axis=1),
    'T_avg': pivot_t_interp.mean(axis=1)
})

# time as a column
agg_t = agg_t.reset_index()
print(agg_t.head())

plt.figure(figsize=(7,5))

plt.plot(agg_t['time']/60, agg_t['T_min'], label='T_min',color='blue')
plt.plot(agg_t['time']/60, agg_t['T_max'], label='T_max',color='red')
plt.plot(agg_t['time']/60, agg_t['T_avg'], label='T_avg',color='black', linestyle='--')

plt.xlabel('Time (minutes)')
plt.ylabel('Temperature (C)')
plt.title('Min, Max, and Average Temperatures Over Time')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

# Calculate average difference between T_max and T_min
avg_temp_diff = (agg_t['T_max'] - agg_t['T_min']).mean()
print(f'Average temperature difference (T_max - T_min): {avg_temp_diff:.2f} °C')

# current (might be scaled to something)

window_size = 500
df_eol['I_avg'] = df_eol['I'].rolling(window=window_size, center=True).mean()

plt.figure(figsize=(7,5))
plt.plot(df_eol['time']/60, df_eol['I'], alpha=0.3, label='Current')
plt.plot(df_eol['time']/60, df_eol['I_avg'], color='black', label='Rolling Avg')

plt.xlabel('Time (minutes)')
plt.ylabel('Current (A)')
plt.title('Current vs Time')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

"""# Dataset 2"""

df_new_orig = pd.read_csv('/content/drive/Othercomputers/My MacBook Air/Desktop/smart/20250710_110851-Anahein-Riverside.csv')
df_new_orig.head()

# unit conversions
df_new = df_new_orig.copy()
df_new = df_new.rename(columns={'creationDateTime': 'time', 'I_IEP_POS': 'I'})
df_new['BMS_TEMP'] = df_new['BMS_TEMP']/10 #degC
df_new['BMS_STRING_V'] = df_new['BMS_STRING_V']/1000 #V
df_new['time'] = df_new['time']/(1000) #second

# Calculate min and max for each column
min_max_values = df_new.agg(['min', 'max'])

# Print the results
print(min_max_values)

# delta timestamps

gap = df_new.time.diff()
plt.plot(gap)
print(gap.unique())

# voltage
plt.figure(figsize=(7,5))

for index in sorted(df_new['BMS_STRING_INDEX'].unique()):
    df_subset = df_new[df_new['BMS_STRING_INDEX'] == index]
    plt.plot(df_subset['time']/60, df_subset['BMS_STRING_V'], label=f'{index}')

plt.xlabel('Time (minutes)')
plt.ylabel('BMS_STRING_V (V)')
plt.title('String Voltage vs Time (per string)')
# plt.legend(title='BMS_STRING_INDEX')
plt.grid(True, linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

# Pivot for voltage
pivot_v = df_new.pivot(index='time', columns='BMS_STRING_INDEX', values='BMS_STRING_V')

# Interpolate missing data along the time index
pivot_v_interp = pivot_v.interpolate(method='linear', limit_direction='both')

# Aggregate across strings (columns) for each time
agg_v = pd.DataFrame({
    'V_min': pivot_v_interp.min(axis=1),
    'V_max': pivot_v_interp.max(axis=1),
    'V_avg': pivot_v_interp.mean(axis=1)
})

# time as a column
agg_v = agg_v.reset_index()

print(agg_v.head())

plt.figure(figsize=(7,5))

plt.plot(agg_v['time']/60, agg_v['V_min'], label='V_min',color='blue')
plt.plot(agg_v['time']/60, agg_v['V_max'], label='V_max',color='red')
plt.plot(agg_v['time']/60, agg_v['V_avg'], label='V_avg',color='black', linestyle='--')

plt.xlabel('Time (minutes)')
plt.ylabel('Voltage (V)')
plt.title('Min, Max, and Average Voltages Over Time')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

plt.figure(figsize=(10,7))
sns.heatmap(pivot_v_interp.T, cmap='coolwarm', cbar_kws={'label': 'Voltage (V)'})
plt.xlabel('Time Index (s)')
plt.ylabel('String Index')
plt.title('Voltage Heatmap across strings')
plt.tight_layout()
plt.show()

# temperature
plt.figure(figsize=(7,5))

for index in sorted(df_new['BMS_TEMP_INDEX'].unique()):
    df_subset = df_new[df_new['BMS_TEMP_INDEX'] == index]
    plt.plot(df_subset['time']/60, df_subset['BMS_TEMP'], label=f'{index}')

plt.xlabel('Time (minutes)')
plt.ylabel('BMS_TEMP (C)')
plt.title('Temperature vs Time (per sensor)')
# plt.legend(title='Sensor #')
plt.grid(True, linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

string_means = pivot_v.mean(axis=0)

overall_mean = string_means.mean()
deviation_from_mean = string_means - overall_mean

print(overall_mean)
print(deviation_from_mean.sort_values())
print(f'Maximum deviation from mean: {deviation_from_mean.max()*1000:.2f} mV')
print(f'Minimum deviation from mean: {deviation_from_mean.min()*1000:.2f} mV')

# Pivot for temperature
pivot_t = df_new.pivot(index='time', columns='BMS_TEMP_INDEX', values='BMS_TEMP')

# Interpolate missing data along the time index
pivot_t_interp = pivot_t.interpolate(method='linear', limit_direction='both')

agg_t = pd.DataFrame({
    'T_min': pivot_t_interp.min(axis=1),
    'T_max': pivot_t_interp.max(axis=1),
    'T_avg': pivot_t_interp.mean(axis=1)
})

# time as a column
agg_t = agg_t.reset_index()
print(agg_t.head())

plt.figure(figsize=(7,5))

plt.plot(agg_t['time']/60, agg_t['T_min'], label='T_min',color='blue')
plt.plot(agg_t['time']/60, agg_t['T_max'], label='T_max',color='red')
plt.plot(agg_t['time']/60, agg_t['T_avg'], label='T_avg',color='black', linestyle='--')

plt.xlabel('Time (minutes)')
plt.ylabel('Temperature (C)')
plt.title('Min, Max, and Average Temperatures Over Time')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

# Calculate average difference between T_max and T_min
avg_temp_diff = (agg_t['T_max'] - agg_t['T_min']).mean()
print(f'Average temperature difference (T_max - T_min): {avg_temp_diff:.2f} °C')

sensor_means = pivot_t_interp.mean(axis=0)

# Calculate overall mean and std of sensor averages
overall_mean = sensor_means.mean()
overall_std = sensor_means.std()
threshold = 2

# Identify sensors with average significantly different from group mean
sensor_outliers = sensor_means[np.abs(sensor_means - overall_mean) > (threshold * overall_std)]

print("Sensors with average temperature outliers:\n", sensor_outliers)

plt.figure(figsize=(10,7))
sns.heatmap(pivot_t_interp.T, cmap='coolwarm', cbar_kws={'label': 'Temperature (°C)'})
plt.xlabel('Time Index (s)')
plt.ylabel('Sensor Index')
plt.title('Temperature Heatmap across Sensors')
plt.tight_layout()
plt.show()

sensor_means = pivot_t.mean(axis=0)

# plt.figure(figsize=(7,5))
# plt.bar(sensor_means.index, sensor_means.values)
# plt.xlabel('Sensor Index')
# plt.ylabel('Average Temperature (°C)')
# plt.title('Average Temperature per Sensor')
# plt.tight_layout()
# plt.show()

overall_mean = sensor_means.mean()
deviation_from_mean = sensor_means - overall_mean

print(overall_mean)
print(deviation_from_mean.sort_values())
print(f'Maximum deviation from mean: {deviation_from_mean.max():.2f} °C')
print(f'Minimum deviation from mean: {deviation_from_mean.min():.2f} °C')

# current (might be scaled to something)
window_size = 500
df_new['I_avg'] = df_new['I'].rolling(window=window_size, center=True).mean()

plt.figure(figsize=(7,5))
plt.plot(df_new['time']/60, df_new['I'], alpha=0.3, label='Current')
plt.plot(df_new['time']/60, df_new['I_avg'], color='black', label='Rolling Avg')

plt.xlabel('Time (minutes)')
plt.ylabel('Current (A)')
plt.title('Current vs Time')
plt.grid(True, linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

